version: 0.2

env:
  variables:
    BACKEND_IMAGE_NAME: product-backend
    FRONTEND_IMAGE_NAME: product-frontend
  secrets-manager:
    DOCKERHUB_USERNAME: dockerhub:username
    DOCKERHUB_PASSWORD: dockerhub:password

phases:
  install:
    commands:
      - set -e  # Exit immediately on error

  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - VERSION_TAG=v$CODEBUILD_BUILD_NUMBER
      - echo "Version tag is $VERSION_TAG"

  build:
    commands:
      - echo Building backend image...
      - cd Products_Backend
      - docker build -t $BACKEND_IMAGE_NAME:$VERSION_TAG .
      - docker tag $BACKEND_IMAGE_NAME:$VERSION_TAG $DOCKERHUB_USERNAME/$BACKEND_IMAGE_NAME:$VERSION_TAG
      - cd ..

      - echo Building frontend image...
      - cd Products_UI
      - docker build -t $FRONTEND_IMAGE_NAME:$VERSION_TAG .
      - docker tag $FRONTEND_IMAGE_NAME:$VERSION_TAG $DOCKERHUB_USERNAME/$FRONTEND_IMAGE_NAME:$VERSION_TAG
      - cd ..

  post_build:
    commands:
      - echo Pushing backend image...
      - docker push $DOCKERHUB_USERNAME/$BACKEND_IMAGE_NAME:$VERSION_TAG
      - echo Pushing frontend image...
      - docker push $DOCKERHUB_USERNAME/$FRONTEND_IMAGE_NAME:$VERSION_TAG

      - echo Copying deployment files to root for artifacts...
      - cp Products_Backend/backend-deployment.yaml .
      - cp Products_UI/frontend-deployment.yaml .
      - echo Files in root after copy:
      - ls -lh

artifacts:
  files:
    - backend-deployment.yaml
    - frontend-deployment.yaml
