// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductService.Data;

#nullable disable

namespace ProductService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250618142648_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductService.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Latest Apple iPhone with 128 GB storage",
                            ImageUrl = "https://via.placeholder.com/300x200?text=iPhone+16e",
                            Name = "iPhone 16e 128 GB",
                            Price = 56000m,
                            Stock = 50
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Mid-range Samsung with 5G support",
                            ImageUrl = "https://via.placeholder.com/300x200?text=Galaxy+A35",
                            Name = "Samsung Galaxy A35 5G",
                            Price = 150000m,
                            Stock = 40
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Flagship killer OnePlus 12",
                            ImageUrl = "https://via.placeholder.com/300x200?text=OnePlus+12",
                            Name = "OnePlus 12",
                            Price = 64999m,
                            Stock = 60
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
